### DISCUSSION TITLE
error: `no go files found in root search path`

### DISCUSSION THREAD

**Discussion by LandonTClipp** [vektra/mockery#636] [General]
This is a discussion thread for this error. 

[Documentation found here](https://vektra.github.io/mockery/latest/notes/#error-no-go-files-found-in-root-search-path)

**Comment by echarrod** [comment]
I have a repo where my main module I want to mock for is a few folders deep. I am getting this error when I place mockery.yaml at the root, even if I have go files at the root. 

Is there a way I can keep this at the root, rather than in the sub-folder?

**Reply by LandonTClipp** [reply]
There is not, you have to place it at the location of the package you’re importing. The go package parser requires this or else it will not download the package unfortunately.

**Comment by fahminlb33** [comment]
I have the same issue. My solution to this is to create a new main func on my project root.

Project structure:

```
cmd
   /server
   /server/main.go
pkg
   /config
   /config/config.go
   /...
domain
   /users/...
   /products/...
   /...
test_spec.go --> to allow mockery to generate mocks
```

.mockery.yml

```yaml
all: true
testonly: false
inpackage: true
with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    my-package:
        config:
            recursive: true
```

test_spec.go

```go
package main

import "my-package/pkg/config"

// this is required to generate mock files
// this file is not used anywhere
func main() {
	config.Load("")
}
````

**Reply by dallindavis** [reply]
```
all: true
testonly: false
inpackage: true
with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    my-package:
        config:
            recursive: true
```
Using this pattern, how do I mock only select interfaces? I tried the following but no mocks are getting created.
```
all: true
testonly: false
inpackage: true
with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    my-package:
        config:
            recursive: true
        interfaces:
             MyInterface:
```
