### DISCUSSION TITLE
How to add mocks for internal packages using configuration?

### DISCUSSION THREAD

**Discussion by flymop** [vektra/mockery#664] [Q&A] [answered]
Hi,
  I'm using mockery configuration here:
```
dir: "mocks/{{.PackagePath}}"
keeptree: False
filename: "{{.InterfaceName}}_mock.go"
mockname: "{{.InterfaceName}}Mock"
packages:
  my-project/internal/db:
    interfaces:
      Service: {}
```

I'm using `keeptree: False` here, the mockery generates mocks in `my-project/mocks/my-project/internal/db`, but golang toolchain blocks me to import it elsewhere since it's in `internal` package.

while using `keeptree: True`, the mockery generates mocks in `my-projects/internal/db`, it works well in same package, but golang toolchain blocks the import from other package.

Any idea to generate the mocks and I can import it in other packages?

Thanks a head!
