### DISCUSSION TITLE
Generated mock does not properly import dependent structs.

### DISCUSSION THREAD

**Discussion by Tochemey** [vektra/mockery#783] [Q&A] [answered]
What setting do I need to use for the config to include dependent struct needed by the interface?

Previous I was using the following command `mockery  --all --dir hash --keeptree --exported=true --with-expecter=true --inpackage=true --output ./mocks/hash --case snake` and all required types are imported smoothly. Now I am switching to the yaml file and kind of struggling.

**Comment by LandonTClipp** [comment]
You seem to be wanting to place mocks adjacent to your interface. Did you try: https://vektra.github.io/mockery/latest/configuration/#__tabbed_1_2 ?

**Reply by Tochemey** [reply]
@LandonTClipp Thanks for the reply. The expectation is to place mocks in a separate package and when I run the command it works well. The challenge I am having is to translate that command into the yaml file.

**Reply by LandonTClipp** [reply]
Okay I see. Your old command kept the original structure but placed it in `./mocks/hash`. I have migration docs for moving to the new yaml file. The equivalent should be something like this: https://vektra.github.io/mockery/latest/migrating_to_packages/#separate-mocks-directory

The examples should be fairly copy-paste. If you can describe the specific issue you have, I'm willing to help.

**Reply by Tochemey** [reply]
@LandonTClipp Thanks again for the quick reply. This is my use case:
I have an interface containing the following method for instance `Peers(ctx context.Context) ([]*Peer, error)` where `Peer` is a struct in the interface package. The command line is able to generate the mock with a clean import of the `Peer` struct. However I find difficult to convert the following command `mockery  --dir discovery --name Provider --keeptree --exported=true --with-expecter=true --inpackage=true --output ./mocks/discovery --case snake` into the yaml file using the packages feature.

I hope it helps.

**Reply by Tochemey** [reply]
This is how I design the config file:

```yaml
outpkg: mocks
packages:
  github.com/tochemey/goakt/v2/hash:
    config:
    interfaces:
      Hasher:
        config:
          with-expecter: True
          exported: True
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}.go"
          dir: hash
  github.com/tochemey/goakt/v2/discovery:
    config:
    interfaces:
      Provider:
        config:
          with-expecter: True
          exported: True
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}.go"
          dir: discovery
  github.com/tochemey/goakt/v2/internal/cluster:
    config:
    interfaces:
      Interface:
        config:
          with-expecter: True
          exported: True
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}.go"
          dir: cluster

```
