### DISCUSSION TITLE
Mock for a builder interface

### DISCUSSION THREAD

**Discussion by mesirendon** [vektra/mockery#786] [Q&A] [answered]
Hi everyone, I'd like to know what's the best way to mock a builder.

Let me setup the example:

```go
package repository

type (
  myBuilder interface {
    Set() myBuilder
  }

  MyRepo struct {
    builder myBuilder
  }
)

func NewMyRepo(builder myBuilder) *MyRepo {
  return &MyRepo { builder: builder }
}

func(r *MyRepo) DoSomething() error {
  b := r.builder.Set()
  ...
  return nil
}
```

On the other hand I have my `.mockery.yaml` file defining the mockery output as:

```yaml
disable-version-string: True
with-expecter: True
packages:
  github.com/mesirendon/mydomain/go/module/internal/repository:
    config:
      all: True
      outpkg: "mock"
      dir: "{{.InterfaceDir}}/mock"
      filename: "{{.InterfaceName}}_mock.go"
```

I'm having problems as the types don't match.

In the meantime, I can reduce my coverage by not testing the injection of the actual builder. But it would be nice to have everything tested.

Please point me in the right direction.
