### DISCUSSION TITLE
Exclude interfaces from mock generation

### DISCUSSION THREAD

**Discussion by Fogoid** [vektra/mockery#836] [Q&A]
Hello everyone!

As the title suggests, I would like to exclude some interfaces from generation. I'm using the `.mockery.yaml` file to generate the mocks, and I have all the interfaces in the same package, but in separate files. So far, I've tried using the `exclude` and `exclude-regex` properties, but it has not been working for me.

Here is my `.mockery.yaml` file:
```yaml
with-expecter: false
packages:
  mockery-test/interfaces/repositories:
    config:
      all: true
      dir: "repositories/mocks"
      filename: "{{.InterfaceName}}.go"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
  mockery-test/interfaces/services:
    config:
      all: true
      dir: "services/mocks"
      filename: "{{.InterfaceName}}.go"
      outpkg: "mocks"
      mockname: "{{.InterfaceName}}"
```

The files that I would like to exclude are in the package `mockery-test/interfaces/services` with the name "*ToExclude"

Can you lend me a hand? Thanks
