### DISCUSSION TITLE
Cound not import mock packages

### DISCUSSION THREAD

**Discussion by bh4rtp2023** [vektra/mockery#978] [General]
Mockery generates interfaces package, i.e. `mocks`. It could not be imported. VSCode tells an error:
```could not import myproject/mypkg/mocks (no required module provides package "myproject/mypkg/mocks") compiler [BrokenImport] (https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)```

When generating interfaces package inside `mypkg`, it does work.
What's wrong with the first configuration?

**Comment by LandonTClipp** [comment]
It'll be exceedingly difficult to give you an answer without any reproducers or even the YAML config you're using :)

**Comment by bh4rtp2023** [comment]
@LandonTClipp  Thanks for your attention. This is mockery.yaml file:
```
with-expecter: true
issue-845-fix: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName}}_test.go"
mockname: "Mock{{.InterfaceName | firstUpper}}"
outpkg: "mocks"
log-level: debug
packages:
  myproject/pkg:
    config:
      all: true
    interfaces:
      transactionContext:
      clientIdentity:
```
