### ISSUE TITLE
Allow filtering by `interface` name or `package` when using `--config` with mockery `v3`

### ISSUE THREAD

**Issue by anisurrahman75** [vektra/mockery#1023]
Hello everyone 👋

I'm using Mockery v3 with a `mockery.yaml` config file that includes `multiple packages` and `interfaces`. The config works fine and generates all mocks as expected.

However, I’d like to generate `only one specific mock` — either from `a specific package` or for `a specific interface` — without removing the rest from the config.

```yaml
all: false
force-file-write: true
formatter: goimports
log-level: info
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'

packages:
  url-shortener/internal/domain/repository:
    config:
      pkgname: "mocks"
      dir: "./mocks"
      filename: "{{.InterfaceName}}.go"
    interfaces:
      URLRepository: { }
      UserRepository: { }
```

```bash
$ mockery --config mockery.yaml
```

It generates all mocks listed in the YAML.

I was expecting an optional flag like `--name` or `--package` that would limit the generation to a specific interface or package even when using the YAML config.

Is this feature currently available or on the roadmap?

```bash
generate-mocks:
	docker run --rm -v "$(PWD)":/src -w /src $(MOCKERY_IMAGE) --config $(MOCKERY_CONFIG)
```

I'm using make to automate the process. Pardon me my mistake, if I am wrong.
