### ISSUE TITLE
migrate command places exclude-subpkg-regex incorrectly in config

### ISSUE THREAD

**Issue by nahida05** [vektra/mockery#1025]
When using the migrate command to convert a v2 config file to v3, the `exclude` field from the v2 format is translated to `exclude-subpkg-regex`, which is expected. However, in the migrated config, this field is placed under the package section. This breaks expected behavior because exclude-subpkg-regex needs to be defined at the root level of the config to function correctly.

**v2 config file** 

```yaml
with-expecter: true
dir: "{{.InterfaceDirRelative}}/mocks"
outpkg: mocks
packages:
  package_name/internal:
    config:
      recursive: true
      disable-version-string: true
      all: true
      exclude:
        - app/migrate/migrator
        - pkg/tests
```

**generated config file**

```yaml
dir: '{{.InterfaceDirRelative}}/mocks'
pkgname: mocks
template: testify
build-tags: test
filename: "mock_{{.InterfaceName}}.go"
structname: "Mock{{.InterfaceName}}"
packages:
  package_name/internal:
    config:
      all: true
      exclude-subpkg-regex:
        - app/migrate/migrator
        - pkg/tests
      recursive: true
```

**valid config file**

```yaml
dir: '{{.InterfaceDirRelative}}/mocks'
pkgname: mocks
template: testify
build-tags: test
filename: "mock_{{.InterfaceName}}.go"
structname: "Mock{{.InterfaceName}}"
exclude-subpkg-regex: ["package_name/internal/app/migrate/*", "package_name/internal/tests/*"]
packages:
  package_name/internal:
    config:
      all: true
      recursive: true
```

### Steps to Reproduce
Use a v2 config file that contains the exclude field.

Run the mockery migrate command.

Observe the resulting v3 config — exclude-subpkg-regex is placed under package, rather than at the root.

###  Environment
mockery version: v3.2.2
go version: go1.24.2
