### ISSUE TITLE
mockery v3.2.1 broken for variadic functions with multiple return variables

### ISSUE THREAD

**Issue by samborkent** [vektra/mockery#1035]
## Description

When generating a mock some broken code is generated:

```
if returnFunc, ok := ret.Get(0).(func(...string) (int, error)); ok {
	return returnFunc(str)
}
if returnFunc, ok := ret.Get(0).(func(...string) int); ok {
	r0 = returnFunc(str...)
}
```

`returnFunc` is of form `func(...string) (int, error))`, the second parameter takes a variadic string parameter.

In the first if-statement, mockery does not expand `str` using `...`. However, it does do this correctly in the second if-statement.

This is my `mockery.yaml` config (most mocks and package dir omitted as this is not a public project):

```
all: true
dir: ./mocks/{{ .InterfaceDirRelative }}
structname: Mock{{.InterfaceName}}
pkgname: '{{.SrcPackageName}}_mocks'
filename: "{{.InterfaceName | snakecase }}.go"
recursive: true
force-file-write: true
template: testify
packages:
  [package dir]:
    config:
      all: false
    interfaces:
      NewInterface: {}
```

## Reproducer

Reproducible with any interface containing a function with a variadic argument with multiple return variables. For example:

```
type Interface interface {
	Foobar(str ...string) (int, error)
}
```

## Expected behavior

It properly handles variadic arguments for functions with multiple return values.

## Mockery version

`v3.2.1`

## Installation Mechanism

- [] `tool github.com/vektra/mockery/v3`, usage `go tool mockery --config .mockery.yaml --log-level warn`
