### ISSUE TITLE
panic when trying to use anchors

### ISSUE THREAD

**Issue by PiskarevSA** [vektra/mockery#1057]
I used this config with version v3.0.0-beta.2 to generate both mock and stub:
```yaml
template: matryer

# configs presets
anchors: &make_both_mock_and_stub
  configs:
  - template-data:
      stub-impl: false
    filename: mocks_test_exported.go
    structname: "Mock{{.InterfaceName}}"
  - template-data:
      stub-impl: true
    filename: mocks_test_exported.go
    structname: "Stub{{.InterfaceName}}"

# specify an explicit list of mocked interfaces
all: False
packages:
  path/to/repo:
    interfaces:
      MyInterface: *make_both_mock_and_stub
```

I updated to v3.3.1 recently, but received an error:
`FTL app failed error="getting config: unmarshalling config: decoding failed due to the following error(s):\n\n'' has invalid keys: anchors" version=v3.3.1`

I changed `anchors` to `_anchors` to fix an error, but i received panic:
```text
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/knadh/koanf/maps.Merge(0xa92a60?, 0x0)
        /home/sam/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.1/maps.go:114 +0x1bc
github.com/knadh/koanf/maps.Merge(0xc000251290?, 0xc000250ed0)
        /home/sam/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.1/maps.go:127 +0xf3
github.com/knadh/koanf/v2.(*Koanf).merge(0xc000250f60, 0xc000251290, 0xc00008c3c8)
        /home/sam/go/pkg/mod/github.com/knadh/koanf/v2@v2.1.2/koanf.go:416 +0x6b
github.com/knadh/koanf/v2.(*Koanf).Load(0xc000250f60, {0xc7a8e0?, 0xc0000a90e0?}, {0xc7a7f0?, 0x1183760?}, {0x0, 0x0, 0x0?})
        /home/sam/go/pkg/mod/github.com/knadh/koanf/v2@v2.1.2/koanf.go:120 +0x12e
github.com/vektra/mockery/v3/config.NewRootConfig({0xc7e618, 0xc000250e70}, 0xc000248200)
        /home/sam/go/pkg/mod/github.com/vektra/mockery/v3@v3.3.1/config/config.go:189 +0x745
github.com/vektra/mockery/v3/internal/cmd.GetRootApp({0xc7e618, 0xc000250e70}, 0xc000248200)
        /home/sam/go/pkg/mod/github.com/vektra/mockery/v3@v3.3.1/internal/cmd/mockery.go:84 +0x46
github.com/vektra/mockery/v3/internal/cmd.NewRootCmd.func1(0xc000248900?, {0xc0000a8e60?, 0x4?, 0xb2f609?})
        /home/sam/go/pkg/mod/github.com/vektra/mockery/v3@v3.3.1/internal/cmd/mockery.go:42 +0x206
github.com/spf13/cobra.(*Command).execute(0xc000193508, {0xc0000224f0, 0x2, 0x2})
        /home/sam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xabb
github.com/spf13/cobra.(*Command).ExecuteC(0xc000193508)
        /home/sam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x44f
github.com/spf13/cobra.(*Command).Execute(...)
        /home/sam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/vektra/mockery/v3/internal/cmd.Execute()
        /home/sam/go/pkg/mod/github.com/vektra/mockery/v3@v3.3.1/internal/cmd/mockery.go:73 +0x31
main.main()
        /home/sam/go/pkg/mod/github.com/vektra/mockery/v3@v3.3.1/main.go:8 +0xf
exit status 2
```
