### ISSUE TITLE
v3: Template per interface for the same package

### ISSUE THREAD

**Issue by BatelShkolnik** [vektra/mockery#1067]
I've been experimenting with Mockery v3 and tried setting `template: matryer` for a single interface within a package, while keeping the rest of the interfaces in the same package using `template: testify`.

Unfortunately, this didn’t work as expected.

Despite specifying `template: matryer` for the `TelemetryUpdater` interface, Mockery generated the `mocks_telemetry_updater.go` file using the `testify` template instead.

I couldn't find a definitive answer in the documentation about whether this setup is supported, though logically it seems like it should be. Here's my current `.mockery.yaml`:

```yaml
dir: ./internal/tests/mocks
packages:
  github.com/work-org/work-repo/some-package/another-package/internal:
    config:
      pkgname: mocks
      template: testify
      filename: "mocks_internal.go"
      all: true
    interfaces:
      TelemetryUpdater:
        config:
          filename: "mocks_telemetry_updater.go"
          template: matryer
```
