### ISSUE TITLE
Interface aliases wont generate mocks in V3

### ISSUE THREAD

**Issue by LeoNdV001** [vektra/mockery#1073]
## Description

Hello, I've just migrated mockery from v2 to v3.
in v2 every interface in the project was correctly generated.

Now I created a v2 config, which almost result in the same output. But I've a few interfaces referring to a parent interface. (due the use of the google wire package, which doesn't allow the same provider multiple times)

`type InterfaceService pkg.InterfaceClient`

so the `pkg.InterfaceClient` is generated correctly, but the `InterfaceService` is not generated
V2 did generate this correctly.

used config.

```
---
all: true
dir: ".mocks/{{.InterfaceDirRelative}}"
filename: "{{.InterfaceName}}.go"
force-file-write: true
formatter: "goimports"
log-level: "info"
structname: "{{.InterfaceName}}"
pkgname: '{{.SrcPackageName}}'
recursive: true
template: testify
packages:
  github.com/xyz/project/pkg:
    config:
      all: true
template-data:
  unroll-variadic: true
```

## Reproducer

- Create a interface in a parent folder
- create a new file and define a type alias (`type InterfaceService pkg.InterfaceClient`)
- use the provided config

## Expected behavior

I need the type alias to be generated correctly

## Mockery version
`v3.3.6`

## Go version
v1.24.4
