### ISSUE TITLE
Loader changes break vendoring

### ISSUE THREAD

**Issue by tehleach** [vektra/mockery#112]
Just FYI:

We noticed that generating mocks on files that rely on vendored dependencies broke yesterday. Looking through this packages non built-in dependencies, I found [some changes](https://github.com/golang/tools/commit/6c803ab014286e086881c410cba381b02317423c) made to [golang.org/x/tools/go/loader](http://golang.org/x/tools/go/loader) which seem to have shifted absolute path -> relative path. I spent some time trying to make mockery work with these changes, but just ended up vendoring the old commit on [my branch](https://github.com/tehleach/mockery) for now, couldn't figure out how to get it working.

**Comment by mmcloughlin** [comment]
If you're using [glide](https://github.com/Masterminds/glide), this will get you a working version of mockery:

```yaml
- package: github.com/vektra/mockery
  version: 4db903efa8f6a978c8ccee3d4f23e947af878ca9
- package: golang.org/x/tools
  version: c060f04f93f57c44284360be78bb323077183645
  subpackages:
  - go/loader
```
