### ISSUE TITLE
Generate private interface doesn't work

### ISSUE THREAD

**Issue by ijalalfrz** [vektra/mockery#376]
i'm using mockery version 2.7.4, and i have a private interface:

```
type elasticsearchRequest interface {
	Do(ctx context.Context, transport esapi.Transport) (resp *esapi.Response, err error)
}
```
what i did : `mockery --exported --name=elasticsearchRequest`
generated file still use private interface

```
// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	esapi "github.com/elastic/go-elasticsearch/v7/esapi"
	mock "github.com/stretchr/testify/mock"
)

// elasticsearchRequest is an autogenerated mock type for the elasticsearchRequest type
type elasticsearchRequest struct {
	mock.Mock
}
...
```

**Comment by built-by-as** [comment]
I am experiencing this as well

**Comment by guzmonne** [comment]
Bump

**Comment by LandonTClipp** [comment]
I hope that this issue will be resolved by the granular level of control the [packages](https://vektra.github.io/mockery/features/#packages-configuration) configuration feature gives you. Please give that a shot and let me know if it doesn't work.

**Comment by TyPh00nCdr** [comment]
I tried the following with packages configuration (module name `exported-test`):

`main.go`:
```go
package main

type unexported interface {
	Foo()
}

type impl struct{}

func (i impl) Foo() {}

func main() {
	var u unexported
	u = impl{}
	u.Foo()
}
```

`.mockery.yml`:
```yaml
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"

packages:
  exported-test:
    interfaces:
      unexported:
        config:
          exported: True
```

And the generated mock will always be unexported. No matter if I set `inplace: True` or not. It seems like `exported` only works if the mocks will be generated outside the package (default configuration works fine) or directly adjacent to the interface.
