### ISSUE TITLE
Mockery config file to generate specified mocks?

### ISSUE THREAD

**Issue by nielskrijger** [vektra/mockery#428]
Hi mockery! I've been using your library for a few years now and I love it, it never let me down.

Recently I joined a project with thousands of interfaces. Of those +/- 50-75 are mocks generated with Mockery.
Since running `mockery --all` takes way too long in this codebase, so far they have been generated by hand.

The difficulty in maintaing such a large codebase is knowing which interfaces are mocked by mockery, and which are not. Keeping them up-to-date is a bit of a pain.

Because `mockery --all` is not an option, I wondered if there is a readily available config-file setup that we can use in our Makefile? I.e. specify all the mocks we'd like to generate?

Two other reasons why I'm considering this;
- generating mocks on-the-fly would save a big chunk of the diff in our MR/PRs
- despite your great warnings we have some mocks that were altered by developers, re-generating them would break the tests... (don't ask)... having mocks regenerated every now and then would avoid this issue and force devs to fix such things properly

**Comment by borisbsv** [comment]
I'd be extremely interested in this as well, right now we chain some 20 or so mockery invocations to generate our mocks - I'd rather move those into a config file and generate with a single command

**Comment by LandonTClipp** [comment]
There is currently not an option to specify this kind of thing in config. One of the major improvements in v3 that I'm planning is a hierarchical config for interface generation. For instance you might have something like this in config:

```yaml
github.com/vektra/mockery:
  config:
    key1: value1
    key2: value2
  interfaces:
    foo:
      config:
        key1: value5
  children:
    pkg:
      config:
        key2: value3
    cmd:
      config:
        key2: value4
```

With something like this, you could conceivably configure mockery to only operate on what was explicitly specified and nothing else. This has other benefits like being able to generate mocks differently for different packages using hierarchical dict merging, or even generate third-party mocks that aren't in your package.
