### ISSUE TITLE
Mocks generated in unexpected directory

### ISSUE THREAD

**Issue by jbub** [vektra/mockery#562]
Description
-------------

Im testing the recent feature https://github.com/vektra/mockery/discussions/549 to see how it would speed up our setup. Unfortunately it does not seem to respect `inpackage` and `keeptree` anymore and it puts mocks in the `mocks` directory instead of putting them inside respective packages.

Mockery Version
--------

v2.21.1

Golang Version
--------------

go1.20.1

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Using config like this:

```
inpackage: true
inpackage-suffix: true
with-expecter: true
keeptree: true
case: snake
packages:
  mypkg/subpkg1:
    config:
      all: True
  mypkg/subpkg2:
    config:
      all: True
```

2. Run `mockery`

### Expected Behavior

Mocks are generated in respective package.

### Actual Behavior

Mocks are generated in mocks directory.
