### ISSUE TITLE
v2.21.6: `packages` config does not obey `--case snake`

### ISSUE THREAD

**Issue by dgunay** [vektra/mockery#577]
Description
-------------

The files generated using the new `packages` feature don't obey the case config.

Mockery Version
--------

v2.21.6

Golang Version
--------------

go version go1.20.2 darwin/arm64

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

with this config:

```yaml
with-expecter: True
filename: "{{.InterfaceName}}.go"
dir: "mocks"
case: snake
packages:
  your/pkg/here:
    all: True
```

running this command:

```
mockery --with-expecter --all -r --case snake --log-level debug
```

### Expected Behavior

the filenames come out `snake_case.go`

### Actual Behavior

the filenames come out `PascalCase.go`

```
09 Mar 23 11:39 PST INF writing to file dry-run=false file=mocks/Auth.go interface=Auth qualified-name=REDACTED version=v2.21.6
```

**Comment by LandonTClipp** [comment]
This is intended that the `case` variable is not respected. The filenames are being driven from template variables so we just need to add a new variable like:

```yaml
filename: "{{.InterfaceNameSnakeCase}}.go"
```

or something like that. I will update the docs and add this new variable I mentioned.

**Comment by dgunay** [comment]
It's your project of course so I ultimately respect your choice, but doesn't that seem a little odd? You would have to define another template variable for every casing convention you want to support. It seems less surprising (at least to me, personally) for the `case` setting to influence the filename.

**Comment by LandonTClipp** [comment]
If we were to have `case` mutate the value of `InterfaceName`, that makes it a bit more complicated in my head because then the value of `InterfaceName` is not actually the interface name, it's the interface name passed through a casing function. It's a bit more restrictive because what if you wanted config like this:

```yaml
filename: "{{.InterfaceName}}.go`
structname: "Mock{{.InterfaceName}}.go"
case: snake
```

Well now both your filename and the name of the mock struct would both be snake case, which is probably not what is intended.
