### ISSUE TITLE
How to generate project mocks *and* 3rd party mocks

### ISSUE THREAD

**Issue by pawoolley** [vektra/mockery#628]
Is there a way to set up `.mockery.yaml` such that mockery will:

1. Generate mocks for all the interfaces in my project.
2. Generate mocks for selectively named interfaces from 3rd party projects, say, in to a `mocks` directory within my project.
2.1. Ignore the `mocks` directory on subsequent runs.

I can seem to achieve requirement 1 with `mockery --all`, and requirement 2 by using the new `packages` config options, but I can't seem to get it to do both things, or at least the config docs aren't making it clear how to set up the yaml.

Can anyone show me an example config set up that does this, please?

**Comment by LandonTClipp** [comment]
> Ignore the mocks directory on subsequent runs.

I'm not sure what you mean by this.

For your other points, yes this is possible with both methods actually, but it's easier with `packages`. You just have to specify the name of the package's path. So if you want to import all io packages, you'd do something like


```
pacakges:
  io:
    config:
      all: true
      recursive: true
  github.com/pawoolley/funrepo:
    config:
      all: false # this is the default anyway
    interfaces:
      Fooer:
      Getter:
      
```

If something about that isn't working please let me know. And feel free to send a PR for the docs if it's not clear.
