### ISSUE TITLE
`inpackage` option has no effect in `packages` mode

### ISSUE THREAD

**Issue by artemmarkaryan** [vektra/mockery#662]
Description
-------------
It seems like when using packages mode, the config option `inpackage` has no effect. 
Say, we have module `github.com/artemmarkaryan/mock-generation/example`, where a file with single interface `Stringer` resides.
When i use legacy mode, the `inpackage` option works just fine, no matter which way the option is passed.
However, when i try to use packages mode, `inpackages` has no effect, no matter where it is stated.

`testonly` doesn't affect file name too, but `inpackage` is my main concern.

Mockery Version
--------
v2.30.16
```
$ mockery --version                                                                                                                                                                                                      
05 Jul 23 00:53 MSK INF Starting mockery dry-run=false version=v2.30.16
```

Golang Version
--------------

```
$ go version                                                                                                                                                                                                             
go version go1.20.5 darwin/arm64
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install

Steps to Reproduce
------------------

1. Create some module
2. Declare interface type in that module
3. Create `.mockery.yaml` config file
4. Put `packages: ...` in config file
5. Put `inpackage: True` in config file
6. Run `$ mockery`
7. May also run `$ mockery --inpackage=true` 

### Expected Behavior

`mock_...go` file is generated and placed alongside the file, where the interface is declared.

### Actual Behavior

`mock_...go` file is generated and placed in `<project-root>/mocks/<module-path>/<package>` directory.

### Tested config

```yaml
inpackage: True
packages:
  github.com/artemmarkaryan/mock-generation/example:
    config:
      inpackage: True
    interfaces:
      Stringer:
        config:
          inpackage: True
```

**Comment by LandonTClipp** [comment]
I haven't heard anything back for a while so I'll close this ticket, but please respond here if you still need help and I'll re-open it.

**Comment by artemmarkaryan** [comment]
Thanks for your reply! I finally managed to configure mockery to generate mocks next to the original interface.

For those, who may encounter this problem, this config worked for me
```yaml
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages: 
    ...
```
