### ISSUE TITLE
Feature Request: InterfaceNameLower as a template variable parameter.

### ISSUE THREAD

**Issue by hohmannr** [vektra/mockery#670]
### Feature Request

I would like to see the addition of a template config variable called `InterfaceNameLower`, so that one could achieve more go standard library-esque file names for the mocks generated by mockery. The standard library  primarily uses lowercase filenames for camelcased structs (e.g. [fakeDB](https://github.com/golang/go/blob/master/src/database/sql/fakedb_test.go#L91)). To achieve the same with mockery, I would like to have the following configuration setup:

```yaml
inpackage: True
filename: "{{.InterfaceNameLower}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}} "
packages:
  github.com/me/my-repo/pkg/datastore:
    interfaces:
      EventStorer:
```

This would the achieve that the following mock file is created: `pkg/datastore/eventstorer_mock.go`

I have not connected a PR for now, since in you state in your CONTRIBUTION guidelines to discuss the matter beforehand.
If this Feature Request will be accepted, I am *willing to do the change myself* and set you up with a PR. It should only be a simple change [here](https://github.com/vektra/mockery/blob/b5592d6410884e37ff7fb32460cb194c8c0038b4/pkg/outputter.go#L212) along with a test-case that covers the new addition.
