### ISSUE TITLE
Not generating mocks when the package only consists of generated files

### ISSUE THREAD

**Issue by amirsalarsafaei** [vektra/mockery#679]
Description
-------------

When there is a package only consisting of generated codes the mockery won't generate mocks for the interfaces. For example, we use SQLC which is a code generator for SQL queries when the package specified for generated querier has only SQLC-generated files the mockery skips the package and doesn't create any mocks.

Mockery Version
--------

v2.32.2
(I tried v2.30.2 too)

Golang Version
--------------

go 1.20

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Mockery Config
-------------------

```yaml
with-expecter: True
packages:
  path/to/your/project:
    config:
      all: True
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: "{{.InterfaceDir}}"
      mockname: "{{.Mock}}{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
```

Steps to Reproduce
------------------

1. In your go project create a new package let's call it `somepackage`
2. In the package create a new go file called `somefile.go`
3. In the file paste a code like below
4. now run mockery 

```go
// Code generated by someGenerator . DO NOT EDIT.

package somepackage

type MyRandomInterface interface {
	SomeRandomFunc()
}
``` 

### Expected Behavior

a file named `mock_myrandominterface.go` to be created

### Actual Behavior

nothing happens

But If you create a file that isn't a generated code and put it beside the first file even if its empty(only contains package name) the mocks will be created. I think this has something to do with mocks packages and there is an condition not the check packages with only generated files.
