### ISSUE TITLE
--replace-type is not mapping packages correctly

### ISSUE THREAD

**Issue by rkoehl05** [vektra/mockery#688]
Description
-------------

I am trying to mock an interface that requires multiple ```--replace-type``` inputs. The target type aliases for these types reside in separate packages but the source internal types are all in the same package. This causes the generate logic to choose the wrong alias when building the mock.

The issue seems to be caused by ```addPackageImportWithName``` only looking at the the package portion of the from ```replaceType``` [here](https://github.com/vektra/mockery/blob/master/pkg/generator.go#L191). It should probably scan all the replace type inputs first to see if there is an explicit type-level mapping and then a follow up scan for package-level mappings.

Mockery Version
--------

2.30.1, 2.32.3

Golang Version
--------------

1.20

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

I set up a reproducer repo [here](https://github.com/rkoehl05/mockrepro). You can run go generate. in it to produce the broken mock.

### Expected Behavior

The ```DeleteResponse``` type should use the ```blob``` alias, not ```blockblob```

### Actual Behavior

```DeleteResponse``` is incorrectly referenced using the ```blockblob``` alias. See [here](https://github.com/rkoehl05/mockrepro/blob/main/example_output.txt#L82) for an example.

**Comment by LandonTClipp** [comment]
Hi thanks for the report, I'll be looking through this to get a better understanding.

**Comment by vitaly-eureka-security** [comment]
Hi. I face a similar issue:
```
packages:
    interfaces:
      IBlockBlobClient:
        config:
          replace-type:
            - 'github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.BlockBlobClientCommitBlockListResponse=blockblob:github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.UploadStreamResponse'
            - 'github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.BlobClientDeleteResponse=blob:github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob.DeleteResponse'
```

Instead of `blob.DeleteResponse` the generated mock contains `blockblob.DeleteResponse`
