### ISSUE TITLE
[Go modules] package mypkg is not in GOROOT (/opt/homebrew/Cellar/go/1.20.7/libexec/src/mypkg)"

### ISSUE THREAD

**Issue by tairosonloa** [vektra/mockery#690]
Description
-------------

Just installed mockery via brew in a M2 MacBook Pro. Added a `.mockery.yml` file at the root of my project (which uses Go modules) with the following content:

```yaml
with-expecter: true
quiet: false
packages:
    pvpc:
        config:
            outpkg: storagemocks
            output: internal/platform/storage/storagemocks
        interfaces:
            ZonesRepository:

```

Then, running mockery from my project root results in the following error:

```
$> mockery

12 Aug 23 12:30 CEST INF Starting mockery dry-run=false version=v2.32.4
12 Aug 23 12:30 CEST INF Using config: /Users/aalonso/workspaces/go-pvpc/.mockery.yaml dry-run=false version=v2.32.4
12 Aug 23 12:30 CEST ERR encountered error when loading package error="-: package pvpc is not in GOROOT (/opt/homebrew/Cellar/go/1.20.7/libexec/src/pvpc)" dry-run=false version=v2.32.4
12 Aug 23 12:30 CEST ERR unable to parse packages error="error occurred when loading packages" dry-run=false version=v2.32.4
```

I checked that the package name is correct, obviously.

```
$> go env

GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/aalonso/Library/Caches/go-build"
GOENV="/Users/aalonso/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aalonso/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aalonso/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.7/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/aalonso/workspaces/go-pvpc/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0d/1q2491w17v94p9ln2f5g8r1h0000gn/T/go-build985208085=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Mockery Version
--------
v2.32.4

Golang Version
--------------
go1.20.7 darwin/arm64

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [X] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Have a Go modules project outside `GOROOT` (I have it in an arbitrary path)
2. Create the above-mentioned `.mockery.yml` file in the project root, referencing an existing interface for an existing module of the project
3. Run `mockery` without extra arguments in a terminal.

### Expected Behavior

Mocks to be created

### Actual Behavior

It failed with error `package pvpc is not in GOROOT (/opt/homebrew/Cellar/go/1.20.7/libexec/src/pvpc)`

**Comment by LandonTClipp** [comment]
Is `pvpc` the fully qualified name of the package?

**Comment by tairosonloa** [comment]
This is my project structure (omitted other some unrelated elements/folders):

```
./
|- go.mod
|- internal/
    |- prices_zone.go
    |- ...
...
```

In my `go.mod` file:

```go
module go-pvpc

go 1.20

require (
    // direct deps
    // ...
)

require (
    // indirect deps
    // ...
)
```

In my `prices_zone.go` file:

```go
package pvpc

import (
    // ...
)

// ...

type ZonesRepository interface {
	GetByID(ctx context.Context, id string) (Zone, error)
}

// ...

```

Tried both, `go-pvpc` (from `go.mod` file) and `pvpc` (from the file `prices_zone.go` that defines the interface) as package name in the `.mockery.yml` file. Both generates the same error message commented initially.

**Comment by LandonTClipp** [comment]
The package declared in your go.mod is not the same as what you've defined in .mockery.yaml. Could you confirm those two are the same?

**Comment by tairosonloa** [comment]
Hey, as I said in my last comment, I have tested both of them. None of these `.mockery.yaml` files are working:

```yaml
with-expecter: true
quiet: false
packages:
    pvpc:
        config:
            outpkg: storagemocks
            output: internal/platform/storage/storagemocks
        interfaces:
            ZonesRepository:
```

Outputs:

```
17 Aug 23 12:07 CEST INF Starting mockery dry-run=false version=v2.32.4
17 Aug 23 12:07 CEST INF Using config: /Users/aalonso/workspaces/go-pvpc/.mockery.yaml dry-run=false version=v2.32.4
17 Aug 23 12:07 CEST ERR use of unsupported options detected. mockery behavior is undefined. dry-run=false unsupported-fields={"case":"underscore"} url=https://vektra.github.io/mockery/v2.32/configuration/#parameter-descriptions version=v2.32.4
17 Aug 23 12:07 CEST ERR encountered error when loading package error="-: package pvpc is not in GOROOT (/opt/homebrew/Cellar/go/1.20.7/libexec/src/pvpc)" dry-run=false version=v2.32.4
17 Aug 23 12:07 CEST ERR unable to parse packages error="error occurred when loading packages" dry-run=false version=v2.32.4
error occurred when loading packages
```

And in the other hand

```yaml
with-expecter: true
quiet: false
packages:
    go-pvpc:
        config:
            outpkg: storagemocks
            output: internal/platform/storage/storagemocks
        interfaces:
            ZonesRepository:

```

Outputs

```
17 Aug 23 12:06 CEST INF Starting mockery dry-run=false version=v2.32.4
17 Aug 23 12:06 CEST INF Using config: /Users/aalonso/workspaces/go-pvpc/.mockery.yaml dry-run=false version=v2.32.4
17 Aug 23 12:06 CEST ERR use of unsupported options detected. mockery behavior is undefined. dry-run=false unsupported-fields={"case":"underscore"} url=https://vektra.github.io/mockery/v2.32/configuration/#parameter-descriptions version=v2.32.4
17 Aug 23 12:06 CEST ERR encountered error when loading package error="-: package go-pvpc is not in GOROOT (/opt/homebrew/Cellar/go/1.20.7/libexec/src/go-pvpc)" dry-run=false version=v2.32.4
17 Aug 23 12:06 CEST ERR unable to parse packages error="error occurred when loading packages" dry-run=false version=v2.32.4
error occurred when loading packages```

**Comment by tairosonloa** [comment]
Added here a minimal reproduction of my code. I testedthat I'm getting the same error message there:

https://github.com/tairosonloa/mockery-issue-690

**Comment by LandonTClipp** [comment]
So according to your file layout, there is nothing you could import at `go-pvpc` because there are no go files at the root path. If you want to import your internal package you need `go-pvpc/internal`.

**Comment by tairosonloa** [comment]
Hi @LandonTClipp.

You're right, I misconfigured it.

Everything is working fine now. This is my final working `.mockery.yml` for the records.

```yaml
with-expecter: true
quiet: false
packages:
    go-pvpc/internal:
        config:
            mockname: "{{.InterfaceName}}"
            filename: "{{.InterfaceNameSnake}}.go"
            outpkg: storagemocks
            dir: internal/platform/storage/storagemocks
        interfaces:
            PricesRepository:
            PricesZonesRepository:
```

Thank you very much for your help 😃
