### ISSUE TITLE
tags are not applied to generated mocks

### ISSUE THREAD

**Issue by evgeny-myasishchev** [vektra/mockery#691]
Description
-------------

Tags are not applied to generated mocks.

Mockery Version
--------

```sh
$ mockery --version
13 Aug 23 10:00 CEST INF Starting mockery dry-run=false version=v2.32.4
13 Aug 23 10:00 CEST INF Using config: /projects/poc-mockery/.mockery.yaml dry-run=false version=v2.32.4
v2.32.4
```

Golang Version
--------------

```sh
$ go version
go version go1.21.0 darwin/arm64
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [X] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create config similar to below:
```yaml
tags: "mock"
packages:
  poc-mockery/pkg/services/oauthstorage:
    interfaces:
      Storage:
```

2. Generate mocks with `mockery` command (no args)

### Expected Behavior

Expected generated file to have `mock`  build tags

### Actual Behavior

No build tags are added. Just the `Code generated....` header
