### ISSUE TITLE
v3 migration guide is confusing

### ISSUE THREAD

**Issue by zekth** [vektra/mockery#703]
Description
-------------
There's currently deprecation message to move to `packages` feature. However moving from legacy options like `--all` and `keepTree` attributes is not an easy path. It would be nice to have an example to properly move forward.
Like from:
```yaml
inpackage: True
testonly: False
with-expecter: True
keeptree: True
```
to:
```yaml
with-expecter: True
inpackage: True
inpackage-suffix: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: true
packages:
  github.com/zekth/mypkg: {}
```

In addition we should really document / alias the `internal` part which was automatically done in the legacy way.
