### ISSUE TITLE
error when loading package, can only [...] in module-aware mode

### ISSUE THREAD

**Issue by devnev** [vektra/mockery#706]
Description
-------------

Getting an error about loading packages and module-aware mode when running mockery, see below

Mockery Version
--------

```
$ grep mockery go.mod go.sum
go.mod:	github.com/vektra/mockery/v2 v2.33.3
go.sum:github.com/vektra/mockery/v2 v2.33.2 h1:znIUwQ3FxnA5jvPy8irYBoiIqMZhuOJhoPOJYNoTJqU=
go.sum:github.com/vektra/mockery/v2 v2.33.2/go.mod h1:9lREs4VEeQiUS3rizYQx1saxHu2JiIhThP0q9+fDegM=
go.sum:github.com/vektra/mockery/v2 v2.33.3 h1:Bahxn87cpbh10fsHhw9671ING/v4dc/53KuLpx0L7I8=
go.sum:github.com/vektra/mockery/v2 v2.33.3/go.mod h1:9lREs4VEeQiUS3rizYQx1saxHu2JiIhThP0q9+fDegM=
```

Golang Version
--------------

```
$ go version
go version go1.21.0 darwin/amd64
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [ ] go install
- [x] Other: go get / go run

Steps to Reproduce
------------------

I'm just trying out mockery's config mode and created the following config in the root of my repository, next to the `go.mod` file

```
packages:
  github.com/....
    config:
      all: true
      inpackage: true
      include-auto-generated: false
      filename: "mock_{{.InterfaceName}}_test.go"
      recursive: true
      dir: "{{.PackagePath}}"
```

I've run `go get -u github.com/vektra/mockery/v2`, and when I run `go run github.com/vektra/mockery/v2` I get the following error:

```
18 Sep 23 17:54 BST ERR encountered error when loading package error="-: can only use path@version syntax with 'go get' and 'go install' in module-aware mode" dry-run=false version=v2.33.3
18 Sep 23 17:54 BST ERR unable to parse packages error="error occurred when loading packages" dry-run=false version=v2.33.3
```

Unfortunately I don't even know which package it was trying to load, so I'm having difficulty narrowing down the reproduction steps

### Expected Behavior

No error

### Actual Behavior

See above
