### ISSUE TITLE
unnecessary mock for type definition of func

### ISSUE THREAD

**Issue by FLAGLORD** [vektra/mockery#716]
Description
-------------
When using the designing pattern of Option Pattern, there will be some code below:
```go
// unexported option
type fooOptions struct{
  // some fields
  // ...
}

// Exported function type
type FooOption func(opt *fooOptions)
```
`mockery` will produce code below:
```go
// FooOption is an autogenerated mock type for the FooOption type
type FooOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: opt
func (_m *FooOption) Execute(opt *common.fooOptions) {
	_m.Called(opt)
}

// NewFooOption creates a new instance of FooOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFooOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *FooOption {
	mock := &FooOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
```
It import a unexported struct. Is it a expected behavior? IMO, `mockery` should not produce a mock for `fooOptions` as it is not a interface.
 
Mockery Version
--------

v2.34.0

Golang Version
--------------

1.20

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. [First Step]
2. [Second Step]
3. [etc]

### Expected Behavior

[what you expect to happen]

### Actual Behavior

[what actually happened]

**Comment by LandonTClipp** [comment]
Mockery can mock plain functions. What's your config? I wouldn't say this is unexpected.

**Comment by FLAGLORD** [comment]
Thanks for your reply. This is my config:
```yaml
with-expecter: false
all: true
filename: "{{.InterfaceNameSnake}}.go"
outpkg: mock{{.PackageName}}
mockname: "{{.InterfaceName}}"
dir: test/mock/{{trimPrefix .InterfaceDirRelative "pkg/"}}
packages:
  packageNameA:
    config:
      recursive: true
```
Is there any way to skip mock for plain functions?
