### ISSUE TITLE
Add exclude-regex or similar mechanism to ignore certain types

### ISSUE THREAD

**Issue by kbolino** [vektra/mockery#718]
Description
-------------

Currently, to define which _types_ (not _packages_) to generate mocks for using the new configuration syntax, there seem to be three options: specify each type, set `all: true`, or set `include-regex` to a regular expression. However, negating a regular expression is not possible in general, and so there is no way to configure mockery to generate mocks for all types _except_ certain ones.

In my particular case, I have a type like the following:

```go
type Option func(*privateStructType)
```

I configure mockery to generate mocks in another package, and so it is impossible to have a mock for this type. However, without enumerating all of the other interface types instead, I see no way to disable mock generation for this type. What I'd like to see is something like an `exclude-regex` option (the inverse of `include-regex`), an `ignore` type-specific option, or some similar mechanism to prevent this type from being mocked.

A temporary solution might have been to specify a never-used build tag on that type only, but when trying that, I ran into https://github.com/vektra/mockery/issues/691 instead.

Mockery Version
--------

```console
% mockery --version
08 Oct 23 17:06 EDT INF couldn't read any config file version=v2.34.2
08 Oct 23 17:06 EDT INF Starting mockery dry-run=false version=v2.34.2
08 Oct 23 17:06 EDT INF Using config:  dry-run=false version=v2.34.2
v2.34.2
```

Golang Version
--------------

```console
% go version
go version go1.21.2 darwin/arm64
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [X] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

Not a bug, but here's my mockery config for illustration (exact package name is redacted):

```yaml
all: true
dir: "{{ .InterfaceDir }}/mocks"
filename: "{{ .InterfaceName }}.go"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
with-expecter: true
packages:
  example.com/package:
    config:
      exclude: [mocks]
      recursive: true
```
