### ISSUE TITLE
Logging warning when mock config is orphaned

### ISSUE THREAD

**Issue by bentcoder** [vektra/mockery#764]
Mockery Version
--------

`v2.42.0`

Golang Version
--------------

`go1.22.0 amd64`

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create an interface
2. Add it to config file
3. Run mockery to create mock
4. Manually delete or comment out interface
5. Rerun mockery command

### Expected Behavior

Since interface doesn't exists anymore, I would have expected mockery command to error or something because there is a misleading/redundant reference in config.

### Actual Behavior

Physical mock file is still in the codebase but unfortunately it is redundant because there is no interface for it anymore.

```
quiet: false
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName|camelcase}}"
filename: "{{.InterfaceName|snakecase}}.go"
outpkg: mocks

packages:
  github.com/myself/app/src/service:
    interfaces:
      MyInterface:

```
