### ISSUE TITLE
Configuration option `inpackage` is not functioning as expected

### ISSUE THREAD

**Issue by emreler** [vektra/mockery#777]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Golang, clearing your local golang package cache, and re-building mockery using the _latest_ Golang version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------

`inpackage` config option is not used when used under `packages`

Mockery Version
--------

`2.43.0`

Golang Version
--------------

`1.22.2`

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Use the `package` configuration method
2. Create a go module, e.g. `github.com/emreler/foo`
3. Define an interface in a subpackage, e.g. `github.com/emreler/foo/bar`
4. Create a `.mockery.yaml` config file like provided below
5. Run mockery

Config:
```yaml
packages:
  github.com/emreler/foo/bar:
    config:
      all: true
      with-expecter: true
      inpackage: true
```

### Expected Behavior

Mock file to be created under `github.com/emreler/foo/bar`

### Actual Behavior

Mock file is created under `github.com/emreler/mocks/github.com/emreler/foo/bar`

The issue seems to be not there when using the old configuration method, e.g. like below:

```yaml
inpackage: true
name: studentStore
recursive: true
```
