### ISSUE TITLE
Unable to generate interface type from another interface

### ISSUE THREAD

**Issue by FournyP** [vektra/mockery#787]
Description
-------------
Hi, I wanted to write some mock for my interface :
```golang
type ResponseLessUseCase[M any] interface {
	Execute(message *M) *errors.Error
}

type SendEmailVerificationUseCaseInterface ResponseLessUseCase[usermessages.SendEmailVerificationMessage]
```

But only the mock for `ResponseLessUseCase` was created, maybe I miss something ?

Mockery Version
--------

v2.43.2

Golang Version
--------------

v1.22.3

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Install go & mockery last versions
2. Write a golang file that include a generic interface and another interface that is typed as your generic interface
3. Run mockery

### Expected Behavior

A mock for the interface that inherit the generic one

### Actual Behavior

Only the mock of the generic interface

**Comment by FournyP** [comment]
Here is my `.mockery.yaml` config :

```
with-expecter: true
all: true
filename: "mock-{{ .InterfaceName | kebabcase }}.go"
outpkg: mock{{.PackageName}}
mockname: "{{.InterfaceName}}"
dir: tests/mocks/{{trimPrefix .InterfaceDirRelative "pkg/"}}
packages:
  packageA:
    config:
      recursive: true
```
