### ISSUE TITLE
Feature request: pre-commit hooks

### ISSUE THREAD

**Issue by liveFreeOrCode** [vektra/mockery#791]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Golang, clearing your local golang package cache, and re-building mockery using the _latest_ Golang version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------

It would be nice to have supported pre-commit hooks capable of generating mocks as part of the normal CD process. Currently I accomplish this as a local hook, but that local hook uses my local golang installation, and if I have a mockery version installed already, the "additional_dependencies" won't be honored.

```yaml
      - id: generate-mocks
        name: generate mocks
        language: golang
        additional_dependencies:
          - github.com/vektra/mockery/v2@v2.43.2
        entry: mockery
        pass_filenames: false
```

Mockery Version
--------

latest

Golang Version
--------------

go version go1.22.4 linux/amd64

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

**Comment by LandonTClipp** [comment]
Sorry I don't understand the question. Are you asking about _git_ pre-commit hooks?

**Comment by ccoVeille** [comment]
I recognize the pattern of pre-commit.com

So, it's about adding a YAML file to the repository.

I don't think there will be a need to maintain the file on version upgrade. Maybe using `@latest` would be enough.

I can help if you want. I can open a PR.

I have already set up such a thing.

The only thing I'm worried about is the fact, a pre-commit hooks might generate the mock, but I'm unsure how it could stop the commit.

But maybe, I will find it out by testing, or the author of this issue would give us some explanation.

Said, otherwise I can help in coding, the need is clear to me as I know pre-commit tool. But I'm unsure what author wants to achieve exactly.

Adding the generated mocked file to the commit, prevent the commit when the mocked files are not up to date

**Comment by ccoVeille** [comment]
Please note, the work is almost complete with the YAML file provided by @liveFreeOrCode 

So maybe, he is just asking for a GO to code it by himself.

**Comment by LandonTClipp** [comment]
Feel free to open a PR. I have never used this tool so I will need education on how this practically speaking will be used by mockery users. I understand the basic concept based on the docs I read of this tool, but perhaps a PR would help solidify the idea for me, in addition to a description of how pre-commit would be configured in a separate repo to pull the YAML config that we will define here.

**Comment by ccoVeille** [comment]
I will unless @liveFreeOrCode post a message.

@LandonTClipp May I ask you to assign me this issue for now?

**Comment by LandonTClipp** [comment]
Assigned, thank you!

**Comment by liveFreeOrCode** [comment]
👋 Hi @ccoVeille.  Thank you for taking this on.  I usually drop in a feature request first in issues before I start any work to make sure I work out any gotchas with the maintainers, and to see if it's in line with the product's vision.  That said, I probably wasn't going to be able to get to this anytime soon, so I do really appreciate you being able to jump on this.

> The only thing I'm worried about is the fact, a pre-commit hooks might generate the mock, but I'm unsure how it could stop the commit.

pre-commit will block a commit if any of the hooks modify a file.  So once mockery updates or adds a new mock, the pre-commit output will notify the user that this commit hook modified files, and it will stop the commit so the developer can review the changes that were made by mockery.

**Comment by ccoVeille** [comment]
I remembered it was something like that indeed. But I wasn't sure, and was awaiting a feedback from you to know how you were using the local hook you quoted

**Comment by ccoVeille** [comment]
I have a PR opened for months.

- https://github.com/vektra/mockery/pull/795

Except a few people, there was quite no interest in adding pre-commit supports to mockery.

The experimental and iterative implementations are leaving me in a strange state.

Even if I managed to make it works on my machine ™️,  for using a distant install of mockery, apparently the only thing that worked for @sx-klaviyo is to use the code that will run locally installed mockery.

- https://github.com/vektra/mockery/pull/795#issuecomment-2614487519


Here we are reaching a point where this could be simply added to mockery documentation something like this


```yaml
- local:
  - id: generate-mocks-local 
     name: generate mocks with local mockery 
     description: Generate mocks with local mockery 
     language: system 
     entry: mockery 
     types: [go] 
     pass_filenames: false
```

And here, without even having to add a `.pre-commit-hook.yaml` file.

Thus, if there is no way to install mockery latest version via the hook. Supporting this in mockery repository seems pointless to me.

Also, I recently changed my mind about the logic of adding pre-commit to projects, when there is no real gain to add hooks to the project over the fact to use local configuration. I posted my thoughts here on the almost very same discussion about adding pre-commit hook support to gofumpt.

- https://github.com/mvdan/gofumpt/pull/313#issuecomment-2630656856

For all these reasons, I'm closing my PR

- https://github.com/vektra/mockery/pull/795

Not only because this topic is open for ages, that the interest is limited, even mine. So I choose my own battle, and leave away from here.

Maybe @bhundven who started working on a repository about Go pre-commit world, might be interested

https://github.com/bhundven/golang-pre-commit

He announced it here

- https://github.com/dnephin/pre-commit-golang/issues/98#issuecomment-2629718456

**Comment by markus-gerstel-sp** [comment]
I solved this by adding the following to my code repository's `.pre-commit-config.yaml`:

```
  - repo: local
    hooks:
      - id: mockery
        additional_dependencies: ['github.com/vektra/mockery/v3@v3.6.3']
        name: mock code autogeneration
        entry: mockery
        language: golang
        types: [go]
        pass_filenames: false
        args:
          - --log-level=warn
```

Enjoy.
