### ISSUE TITLE
mock generation for non-relative-to-interface dirs

### ISSUE THREAD

**Issue by tobby-s** [vektra/mockery#802]
Description
-------------

when the `dir` config is specified as not relative to the package (doesn't use `{{.InterfaceDir}}` template), the generation is relative to the current working directory rather than the project root (or wherever .mockery.yaml is specified).

Mockery Version
--------

2.42.1

Go Version
--------------

1.22.3

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. write an interface in a package (or set `.mockery.yaml` to mock an interface from an external go module, which is the use-case i'm encountering this issue), have `/mocks` directory exist in project root
2. set `dir` to `mocks` in `.mockery.yaml`, e.g.:
```yaml
with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
packages:
  context:
    interfaces:
      Context:
```
4. run `mockery` in project root then `cd mocks` and run it again

### Expected Behavior

the second `mockery` shouldn't add any new files since config file was not changed between the two runs

### Actual Behavior

new mocks are created in `mocks/mocks`

### Proposal

add a new template that indicates the `.mockery.yaml` location, e.g. `{{.ConfigDir}}`
