### ISSUE TITLE
Recursive mode fails when the root package doesn't contain go files

### ISSUE THREAD

**Issue by sonalys** [vektra/mockery#837]
Description
-------------

A simple example of this issue would be the following:

```
- internal
| - application
| | - app.go
| - api
| | - api.go
```

If I run with recursive mode for internal folder, I get the error:

```bash
ERR package contains no go files error="no go files found in root search path" documentation=https://vektra.github.io/mockery/v2.45/notes/#error-no-go-files-found-in-root-search-path dry-run=false package-path=module/internal version=v2.45.1
```

Mockery Version
--------

2.45

```yaml
with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }} 
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.gen.go"
all: True
packages:
  module/internal:
    config:
      recursive: true
```

Go Version
--------------

1.23.2

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

### Expected Behavior

For mockery to discover the sub-packages and generate mock for them

### Actual Behavior

mockery fails, since the initial package doesn't contain any Go files.
