### ISSUE TITLE
v3: moq, `template-data.skip-ensure` doesn't work with interface `configs`

### ISSUE THREAD

**Issue by ucirello** [vektra/mockery#883]
Description
-------------

`template-data.skip-ensure` doesn't correctly propagate to the rendered template with defined as an item in interface `configs`.

Mockery Version
--------

`version=v3.0.0-alpha.15`

Go Version
--------------

`go version go1.23.4 darwin/arm64`

Installation Method
-------------------
- [x] go install

Steps to Reproduce
------------------

This configuration ignores `skip-ensure`.
```
all: false
recursive: false
template: moq
packages:
  github.com/org/repo/pkg/log:
    config:
      filename: "logger_mock_test.go"
    interfaces:
      Logger:
        configs:
          - pkgname: "subpkg1"
            dir: "./pkg/subpkg1"
          - pkgname: "log"
            dir: "./pkg/subpkg2/log"
            template-data:
              skip-ensure: true
```

This configuration honors `skip-ensure` (but then it disable ensure tests for all emitted moqs)
```
all: false
recursive: false
template: moq
packages:
  github.com/org/repo/pkg/log:
    config:
      filename: "logger_mock_test.go"
      template-data:
          skip-ensure: true
    interfaces:
      Logger:
        configs:
          - pkgname: "subpkg1"
            dir: "./pkg/subpkg1"
          - pkgname: "log"
            dir: "./pkg/subpkg2/log"
```

### Expected Behavior

Expected `skip-ensure` to work in all cases it is declared.

### Actual Behavior

`skip-ensure` only works at top-level configurations.
