### ISSUE TITLE
Issue while generating mocks using the `packages` object and `inpackage: True`

### ISSUE THREAD

**Issue by sumit-anantwar** [vektra/mockery#885]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Go, clearing your local golang package cache, and re-building mockery using the _latest_ Go version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------
I have a very simple package structure.

<img width=300px src="https://github.com/user-attachments/assets/fba8bb5b-b899-487d-84dd-31a36678fc29"/>

I want to create mocks inside the `tweet` and `user` packages.
Below is the content of `.mockery.yaml` 

```yaml
with-expecter: True 
testonly: False
inpackage: True
all: True
```

When I run `mockery` in the project root, I get expected results.

<img width=300px src="https://github.com/user-attachments/assets/e3c273bd-01ca-4c19-92a1-fccfccc4163d"/>

But, I want the filenames to be `snakecase`
So, I change the `.mockery.yaml` file as below.

```yaml
with-expecter: True 
testonly: False
inpackage: True
all: True
filename: "mock_{{ .InterfaceName | snakecase }}.go"
```

When I run `mockery`, I get the below error.

<img width=600px src="https://github.com/user-attachments/assets/8485a09d-81c9-4fb2-8443-7eb29383a3a8"/>

So, I add the `packages` object to the `yml` as below.

```yaml
with-expecter: True 
testonly: False
inpackage: True
all: True
filename: "mock_{{ .InterfaceName | snakecase }}.go"
packages:
  leo-brown/mockery-poc:
    config:
      all: true
      recursive: true
      inpackage: true
```

Now, when I run `mockery` I get this strange output
<img width=300px src="https://github.com/user-attachments/assets/08079b30-39e2-4706-86a2-f134ced95864"/>

Although the filenames are now snakecase, check the package path `mocks/leo-brown/mockery-poc/internal/core/managers`

I can achieve what I want using the CLI
```bash
$ mockery --all --with-expecter --inpackage --case=snake
```

But, being able to use the yaml is much robust.
Please let me know how it can be achieved,

Mockery Version
--------

v2.50.4

Go Version
--------------

go1.22.3 linux/amd64

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [x] Binary Distribution

Steps to Reproduce
------------------

Check the description above.

### Expected Behavior

The mocks be created in the same package, and have snakecase filenames.

<img width=300px src="https://github.com/user-attachments/assets/13bf5554-c16e-40f6-99e6-de4370ba0c0b"/>

### Actual Behavior

Check the description above.

**Comment by LandonTClipp** [comment]
Have you set the `dir` parameter to what you want? 

https://vektra.github.io/mockery/latest/configuration/#parameter-descriptions

If you want to place mocks adjacent to the interfaces, you can follow: https://vektra.github.io/mockery/latest/configuration/#__tabbed_1_2

**Comment by sumit-anantwar** [comment]
@LandonTClipp , Thank you for the reply.
I had tried this.
With this I'm unable to do `all: True` or `mockery --all`
<img width=700px src="https://github.com/user-attachments/assets/26d32f13-c466-4e75-a20c-7c4060f3a46f"/>

And, if I specify the interface to mock, I get an `unable to find` error.
<img width=800px src="https://github.com/user-attachments/assets/3e527f9f-5fef-4500-9bb7-357b1d6fd1b4"/>

**Comment by sumit-anantwar** [comment]
@LandonTClipp 
Check the below `yaml`. It seems to be doing what I want

```yaml
all: True
packages:
  leo-brown/mockery-poc:
    config:
      recursive: True
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      dir: "{{.InterfaceDir}}"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
```
