### ISSUE TITLE
`include-auto-generated: false` seems ignored

### ISSUE THREAD

**Issue by kushuh** [vektra/mockery#920]
I have an `api` package, that contains both OpenAPI definitions (generated using [ogen](https://github.com/ogen-go/ogen)) and actual implementations for those definitions (in separate files).

Ny mockery configuration looks like this

```yaml
packages:
  github.com/my-org/my-module/api:
    config:
      include-regex: '^[A-Z].+'
      include-auto-generated: false
      recursive: false
      outpkg: apimocks
      dir: api/mocks
```

# Actual behavior

When I run `go run github.com/vektra/mockery/v2@v2.52.2`, it picks up the ogen definitions, even though they belong to generated files (`// Code generated by ogen, DO NOT EDIT.` at the top).

I don't want those definitions picked up because:

- I don't use them in the interfaces I want to test (it's the opposite: I implement them)
- ogen generation includes exported interfaces with private methods, that take private (unexported) types as arguments. Mockery files are broken because of this (since they can't import private types).

# Expected behavior

If I set `include-auto-generated: false`, generated files should not be picked up.
