### ISSUE TITLE
Generate mocks for a single interface into multiple target packages

### ISSUE THREAD

**Issue by acyumi** [vektra/mockery#946]
`mockery` is a great tool, but I’m currently facing some issues and would appreciate your advice:

1. If I place the mock implementation code generated by Mockery in a shared package (e.g., mocks), it often causes circular dependency issues. To avoid this, I now generate the mock implementations directly in the same package as the original interfaces.

2. The naming convention for mock files: When named `mock_xxx.go`, these files are treated as `production code` and included in `test coverage reports` during unit testing. To prevent this, I use the `xxx_mock_test.go` naming pattern. However, this approach breaks cross-package dependency resolution.

3. My current workaround involves manually copying the generated mock code to the packages that require it. I wish `mockery` could generate mocks for a single interface into multiple target packages directly through configuration in `.mockery.yaml`.

Does anyone have suggestions for solving these challenges?

**Comment by LandonTClipp** [comment]
I'm not sure which coverage tool you're using but I would hope that you could just exclude filenames that contain mocks? Would that solve your problem?

Another feature that is probably what you're looking for is the `configs:` section you can specify to create multiple mock implementations of the same interface. See the example section [here](https://vektra.github.io/mockery/latest/features/#examples) for details.

In short:

```yaml
packages:
  github.com/vektra/mockery/v2/pkg: 
    interfaces:
      TypesPackage:
      RequesterVariadic:
        config: 
          with-expecter: False 
        configs:
          - mockname: MockRequesterVariadicOneArgument
            unroll-variadic: False
          - mockname: MockRequesterVariadic
```

You can override the `dir` parameter to place it in a different location. You may need to also mess with the `inpackage` parameter for the mock implementation that lies outside of the interface's source package.

I apologize for this being a little unclear, but mockery v3 has a more explicit schema that makes this more obvious: https://pkg.go.dev/github.com/vektra/mockery/v3/config#RootConfig

In fact, v3 allows the same sort of thing: https://pkg.go.dev/github.com/vektra/mockery/v3/config#InterfaceConfig
