### ISSUE TITLE
v3, matryer, TBD: generate mock and stub at the same time

### ISSUE THREAD

**Issue by PiskarevSA** [vektra/mockery#958]
I don't have much experience writing tests yet, especially in go, but I can assume that, depending on the context, mock will be preferred in one part of the tests, and stub in the other. Therefore, it is necessary to provide a choice already at the time of writing the test.

So far, i use this workaround:

```yaml
# mockery v3 required
force-file-write: true
template: matryer

# configs presets
anchors: &make_both_mock_and_stub
  configs:
  - template-data:
      stub-impl: false
    mockname: "Mock{{.InterfaceName}}"
  - template-data:
      stub-impl: true
    mockname: "Stub{{.InterfaceName}}"

# specify an explicit list of mocked interfaces
all: False
packages:
  path/to/repo/internal/pkg/package1:
    interfaces:
      Interface1: *make_both_mock_and_stub
  path/to/repo/internal/pkg/package2:
    interfaces:
      Interface1: *make_both_mock_and_stub
  path/to/repo/internal/pkg/package3:
    interfaces:
      Interface1: *make_both_mock_and_stub
      Interface2: *make_both_mock_and_stub
      Interface3: *make_both_mock_and_stub
      Interface4: *make_both_mock_and_stub
```
```golang
// gen:
type MockInterface1 struct {)
type StubInterface1 struct {)

// usage:
var mock Interface1 = &MockInterface1{}
var stub Interface1 = &StubInterface1{}
```

TBD simplify config file (replace parameter stub-impl with gen-stub, maybe also add stubname):

```yaml
# mockery v3 required
force-file-write: true
template: matryer
template-data:
  gen-stub: true
#  mockname: default: "Mock{{.InterfaceName}}"
#  TBD add stubname: default: "Stub{{.InterfaceName}}"

# specify an explicit list of mocked interfaces
all: False
packages:
  path/to/repo/internal/pkg/package1:
    interfaces:
      Interface1:
  path/to/repo/internal/pkg/package2:
    interfaces:
      Interface1:
  path/to/repo/internal/pkg/package3:
    interfaces:
      Interface1:
      Interface2:
      Interface3:
      Interface4:
```

TBD implementation

```golang
// .. alternative 1: duplicate code, no constructors, easier to use (recommended)

// gen:
type MockInterface1 struct {)
type StubInterface1 struct {)

// usage:
var mock Interface1 = &MockInterface1{}
var stub Interface1 = &StubInterface1{}

// .. alternative 2: add parameter and constructors, harder to use (not recommended)

// gen:
type MockInterface1 struct {
    stub bool
}

func NewMockInterface1() *MockInterface1 {
    return &MockInterface1{}
}
func NewStubInterface1() *MockInterface1 {
    return &MockInterface1{
        stub: true,
    }
}

// usage:
var mock Interface1 = NewMockInterface1()
var stub Interface1 = NewStubInterface1()

// .. alternative 3: add function Stub(), so an explicit method call makes the use of a stub
//    more noticeable, meaning there is less chance of typos.

// gen:
type MockInterface1 struct {
    stub bool
}

func (i *MockInterface1) Stub() *MockInterface1 {
    i.stub = true
    return i
}

// usage:
var mock Interface1 = &MockInterface1{}
var stub Interface1 = (&MockInterface1{}).Stub() // it turned out to be a not very convenient syntax,
                                                 // but you can come up with something nicer.

// .. alternative 4..N: your suggestions
```

**Comment by LandonTClipp** [comment]
Hmm this is an interesting idea. The tricky requirement we're abutting against is that the matryer mocks need to be backwards compatible with the `matryer/moq` project. This is a practical concern to encourage projects that use `matryer/moq` to switch over to mockery. To be honest, your "workaround" is pretty much how I would expect this to be configured. I hesitate to add any new features like what you're suggesting without really strong justifications.

**Comment by PiskarevSA** [comment]
ok, i understand. Is it possible to simplify config at least (support top-level configs section)

simplified config i want to have:

```
# mockery v3 required
force-file-write: true
template: matryer

# configs presets
configs:
- template-data:
    stub-impl: false
  mockname: "Mock{{.InterfaceName}}"
- template-data:
    stub-impl: true
  mockname: "Stub{{.InterfaceName}}"

# specify an explicit list of mocked interfaces
all: False
packages:
  path/to/repo/internal/pkg/package1:
    interfaces:
      Interface1:
  path/to/repo/internal/pkg/package2:
    interfaces:
      Interface1:
  path/to/repo/internal/pkg/package3:
    interfaces:
      Interface1:
      Interface2:
      Interface3:
      Interface4:
```

**Comment by LandonTClipp** [comment]
I understand what you're asking, but it's not so simple for the general case. We could certainly have the config model automatically merge your top-level `configs` object into the interface-specific configs, but what happens when we need to merge `configs` with a package-level or interface-level mapping? For example:

```yaml
configs:
- template-data:
    stub-impl: false
  mockname: "Mock{{.InterfaceName}}"
- template-data:
    stub-impl: true
  mockname: "Stub{{.InterfaceName}}"

packages:
  path/to/repo/internal/pkg/package3:
    interfaces:
      Interface1:
        configs:
        - foo:bar
      Interface2:
      Interface3:
      Interface4:
```

What should we do in that case? Should the merge involve a simple slice append such that there are now three elements in `configs`? Or should it be a replacement? I guarantee you that users will want both behavior, so now we need a way to specify which merge strategy to employ for each mapping.

I'm not trying to reject your idea, but I'm highlighting the complexity involved with this and I'm trying to weigh if it's worth it to me to take on an additional maintenance burden for the sake of what is (all things considered) a pretty narrow edge case. 

If there is some simpler way to achieve what you're asking for, I'm definitely willing to listen.
