### ISSUE TITLE
getting config: unmarshalling config: decoding failed due to the following error(s):\n\n'' has invalid keys: install-version

### ISSUE THREAD

**Issue by faenschi** [vektra/mockery#991]
hello

i tried to upgrade a few projects to mockery v3. if i run mockery in a pipeline on gitlab i always get the following error:

```
$ mockery --config .mockery.yaml
2025-04-10T13:38:18.889489327Z FTL app failed error="getting config: unmarshalling config: decoding failed due to the following error(s):\n\n'' has invalid keys: install-version" version=v3.0.0
```

my .mockery.yaml looks like that:

```
all: true
dir: gen/mocks/{{ replaceAll .InterfaceDirRelative "internal" "" }}
structname: '{{.InterfaceName}}'
template: testify
filename: "{{.SrcPackageName}}/{{.InterfaceName}}.go"
force-file-write: true
log-level: debug
packages:
    pathto/repositories:
        config:
            pkgname: repositoryMocks
    pathto/services:
        config:
            pkgname: serviceMocks
```

any ideas?

regards angela
