### ISSUE TITLE
Keep constructors for unexported interfaces unexported too

### ISSUE THREAD

**Issue by jankremlacek** [vektra/mockery#993]
Keeping the `v2` constructor for unexported interface naming the same in `v3` would be lovely.

Example config:

```yml
dir: '{{.InterfaceDir}}'
filename: '{{.InterfaceName | snakecase}}_mock.go'
structname: '{{.InterfaceName}}Mock'
pkgname: '{{.SrcPackageName}}'
template: testify
packages:
  github.com/owner/repo:
    interfaces:
      unexportedInterface:

```

The above `v3` config generates a constructor named `NewunexportedInterfaceMock`. It would be awesome to keep it as it was `v2`, so `newUnexportedInterfaceMock`.

**Comment by LandonTClipp** [comment]
Ah! Yes I think this is definitely desirable. I'll fix this. I'm labeling this as a bug.

**Comment by LandonTClipp** [comment]
@jankremlacek v3.0.2 should fix this for you. It turns out I made a mistake when porting the testify template to v3. Let me know if that works for you.

**Comment by jankremlacek** [comment]
Awesome, thank you 🙏🏻

**Comment by cwhight** [comment]
Related to this, is there still a way to explicitly export unexported interfaces in v3?

**Comment by LandonTClipp** [comment]
Yes of course, the functions available to the config templates is here: https://pkg.go.dev/github.com/vektra/mockery/v3/shared

**Comment by cwhight** [comment]
thanks - forgive me if I'm being stupid here, how would I use that in the v3 config file - I am trying to migrate to v3 without breaking my use existing v2 generated mocks, whereby all mocks are stored in a `mocks` pkg adjacent to the pkg in which the interface is declared:

```
all: false
dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceDir}}.go'
formatter: goimports
structname: '{{.InterfaceName}}'
pkgname: 'mocks'
template: testify
packages:
  ./:
    config:
      all: true
      recursive: true
```
